FROM oven/bun:1 as builder

USER bun
WORKDIR /app
COPY --chown=bun:bun package*.json bun.lockdb ./
ENV NODE_ENV=production
RUN bun install --frozen-lockfile --production \
  && bun run --bun docs:build

FROM caddy:2.7.6-alpine as prod

COPY --from=builder /app/dist /arkanum-docs/
COPY Caddyfile /etc/caddy
HEALTHCHECK --interval=15s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1
