FROM oven/bun:1.2.9 AS builder

ARG CI
ARG CI_COMMIT_PULL_REQUEST

COPY . /app
WORKDIR /app
ENV NODE_ENV=production
RUN bun install --frozen-lockfile
RUN bun run --vite docs:build

FROM caddy:2.9.1-alpine AS prod

COPY --from=builder /app/docs/.vitepress/dist/ /arkanum-docs/
COPY Caddyfile /etc/caddy
HEALTHCHECK --interval=15s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
