depends_on:
  - test

pipeline:
  buildImage:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: gitea.ocram85.com
      repo: gitea.ocram85.com/codeserver/arkanum
      dockerfile: Dockerfile
      auto_tag: true
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
      build_args:
        - VERSION="Tag ${CI_COMMIT_TAG} - Branch ${CI_COMMIT_SOURCE_BRANCH} - PR ${CI_COMMIT_PULL_REQUEST}"
    when:
      event: push
      branch: master

  buildTag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: gitea.ocram85.com
      repo: gitea.ocram85.com/codeserver/arkanum
      dockerfile: Dockerfile
      auto_tag: true
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
      build_args:
        - VERSION="Tag ${CI_COMMIT_TAG} - Branch ${CI_COMMIT_SOURCE_BRANCH} - PR ${CI_COMMIT_PULL_REQUEST}"
    when:
      event: tag
