depends_on:
  - test

steps:
  buildImage:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: gitea.ocram85.com
      repo: gitea.ocram85.com/codeserver/arkanum
      dockerfile: Dockerfile
      auto_tag: true
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: push
      branch: master

  buildTag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gitea.ocram85.com/codeserver/arkanum, ocram85/arkanum
      dockerfile: Dockerfile
      auto_tag: true
      logins:
        - registry: https://gitea.ocram85.com
          username:
            from_secret: gitea_user
          password:
            from_secret: gitea_passwd
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_user
          password:
            from_secret: docker_passwd
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: tag

  GiteaRelease:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: RENOVATE_TOKEN
      base_url: https://gitea.ocram85.com
      title: ${CI_COMMIT_TAG}
      note: "> :bulb: **Note:** See [CHANGELOG.md](src/branch/master/CHANGELOG.md) for recent changes."
    when:
      event: tag
