depends_on:
  - test

variables:
  # deployment targets
  - &publish_repos 'ocram85/arkanum,gitea.ocram85.com/codeserver/arkanum'
  # logins for deployment targets
  - publish_logins: &publish_logins
    # Default DockerHub login
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_user
      password:
        from_secret: docker_passwd
    # Additional Quay.IO login
    - registry: https://gitea.ocram85.com
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
steps:
  buildTestImage:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      #dry_run: true
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: next
      logins: *publish_logins
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: pull_request

  triggerPortainer:
    image: ocram85/portainer-serviceupdate
    settings:
      VERBOSE: true
      URI: "https://portainer.ocram85.com"
      TOKEN:
        from_secret: NEXT_TOKEN
    when:
      event: pull_request
