pipeline:
  DockerBaseImage:
    image: renovate/renovate:34.77-slim
    commands:
      - "renovate"
    secrets:
      - RENOVATE_TOKEN
    environment:
      #LOG_LEVEL: debug
      RENOVATE_PLATFORM: "gitea"
      RENOVATE_ENDPOINT: "https://gitea.ocram85.com"
      RENOVATE_REPOSITORIES: "${CI_REPO}"
      RENOVATE_LABELS: "renovate"
      #RENOVATE_DRY_RUN: "full"
      RENOVATE_TOKEN: "${RENOVATE_TOKEN}"
      RENOVATE_GITHUB_TOKEN_WARN: "false"
    when:
      event:
        - push
      branch:
        - master
        - updDeps
