when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &build_plugin 'woodpeckerci/plugin-docker-buildx:4.2.0'
  # deployment targets
  - &publish_repos 'ocram85/arkanum,gitea.ocram85.com/arkanum/arkanum,ghcr.io/ocram85/arkanum,codeberg.org/arkanum/arkanum'
  # logins for deployment targets
  - publish_logins: &publish_logins
    # Default DockerHub login
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_user
      password:
        from_secret: docker_passwd
    # Additional Quay.IO login
    - registry: https://gitea.ocram85.com
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
    # GitHub Container Registry
    - registry: https://ghcr.io
      username:
        from_secret: github_user
      password:
        from_secret: github_passwd
    # Codeberg
    - registry: https://codeberg.org
      username:
        from_secret: codeberg_user
      password:
        from_secret: codeberg_passwd


steps:
  test:
    image: *build_plugin
    settings:
      dry_run: true
      registry: gitea.ocram85.com
      repo: test
      dockerfile: Dockerfile
      platforms: linux/amd64
      auto_tag: true
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: pull_request
      branch: ${CI_REPO_DEFAULT_BRANCH}

  publish:
    image: *build_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: linux/amd64
      auto_tag: true
      logins: *publish_logins
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: [push, tag, cron]
      branch: ${CI_REPO_DEFAULT_BRANCH}

  build-next:
    image: *build_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: next
      logins: *publish_logins
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: [pull_request]

  gitea-release:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: ci_token
      base_url: https://gitea.ocram85.com
      title: ${CI_COMMIT_TAG}
      note: "> :bulb: **Note:** Please refer to [CHANGELOG.md](src/branch/${CI_REPO_DEFAULT_BRANCH}/CHANGELOG.md) for details."
    when:
      event: [tag]
      branch: ${CI_REPO_DEFAULT_BRANCH}
