depends_on:
  - test

variables:
  # deployment targets
  - &publish_repos 'ocram85/arkanum,gitea.ocram85.com/codeserver/arkanum,ghcr.io/ocram85/arkanum'
  # logins for deployment targets
  - publish_logins: &publish_logins
    # Default DockerHub login
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_user
      password:
        from_secret: docker_passwd
    # Additional Quay.IO login
    - registry: https://gitea.ocram85.com
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
    # GitHub Container Registry
    - registry: https://ghcr.io
      username:
        from_secret: github_user
      password:
        from_secret: github_passwd

steps:
  latest:
    image: woodpeckerci/plugin-docker-buildx:2
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      auto_tag: true
      logins: *publish_logins
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: push
      branch: master

  release:
    image: woodpeckerci/plugin-docker-buildx:2
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile
      auto_tag: true
      logins: *publish_logins
      build_args:
        - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
        - TAG=${CI_COMMIT_TAG}
    when:
      event: tag

  GiteaRelease:
    image: plugins/gitea-release
    settings:
      api_key:
        from_secret: RENOVATE_TOKEN
      base_url: https://gitea.ocram85.com
      title: ${CI_COMMIT_TAG}
      note: "> :bulb: **Note:** See [CHANGELOG.md](src/branch/master/CHANGELOG.md) for recent changes."
    when:
      event: tag
