when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &build_plugin 'woodpeckerci/plugin-docker-buildx:5.0.0'
  # deployment targets
  - &publish_repos 'ocram85/arkanum-docs,gitea.ocram85.com/arkanum/arkanum-docs'
  # logins for deployment targets
  - publish_logins: &publish_logins
    # Default DockerHub login
    - registry: https://index.docker.io/v1/
      username:
        from_secret: docker_user
      password:
        from_secret: docker_passwd
    # Additional Quay.IO login
    - registry: https://gitea.ocram85.com
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_passwd
steps:
  test:
    image: *build_plugin
    settings:
      dry_run: true
      registry: gitea.ocram85.com
      repo: test
      dockerfile: Dockerfile.vitepress
      platforms: linux/amd64
      auto_tag: true
      build_args:
        - CI=${CI}
    when:
      event: pull_request
      branch: ${CI_REPO_DEFAULT_BRANCH}

  publish:
    image: *build_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile.vitepress
      platforms: linux/amd64
      auto_tag: true
      logins: *publish_logins
      #build_args:
      #  - VERSION=${CI_COMMIT_TAG:-PR ${CI_COMMIT_PULL_REQUEST}}
      #  - TAG=${CI_COMMIT_TAG}
    when:
      event: [push, tag, cron]
      branch: ${CI_REPO_DEFAULT_BRANCH}

  build-next:
    image: *build_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile.vitepress
      platforms: linux/amd64
      tag: next
      logins: *publish_logins
      build_args:
        - CI=${CI}
        - CI_COMMIT_PULL_REQUEST=${CI_COMMIT_PULL_REQUEST}
    when:
      event: [pull_request]
