depends_on:
  - ci
  - docs

when:
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: TASK == "release-helper"

steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:3.2.0
    settings:
      debug: true
      git_email: noreply@ocram85.com
      forge_token:
        from_secret: ci_token
